(forall lookup i1 (n1 k1) (n2 v1)
  (implies (not (v1 = 'no_value))
    (exists store i2 (n3 k2 v2) (n4)
      (and
        (k1 = k2)
        (v1 = v2)
        (not (before i1 i2))
        (not (meets i1 i2))
      )
    )
  )
)
